### ISSUE TITLE
Immediate crash on TS3 3.3.0 with TokoVoIP 1_2_2 Windows 10 Pro 1903

### ISSUE THREAD

**Issue by hypertux001** [Itokoyamato/TokoVOIP_TS3#17] opened 2019-06-27 17:53 UTC
Tried reinstalling plugin, removing plugin allowed TS to open fine. As soon as plugin is back in Teamspeak will not open.
Attached TS client log
[ts3dump_1561657605728.zip](https://github.com/Itokoyamato/TokoVOIP_TS3/files/3336046/ts3dump_1561657605728.zip)

**Comment by Itokoyamato** [comment] 2019-06-27 20:41
Duplicate of #16

**Closed by Itokoyamato** 2019-06-27 20:41 UTC
