### ISSUE TITLE
Freeze in game

### ISSUE THREAD

**Issue by LucasR0cha** [Itokoyamato/TokoVOIP_TS3#22] opened 2019-07-02 01:39 UTC
Hello Dylan Thuillier, I'm having problems with this current version.
my players after a while get freeze after opening the chat or any panel inside the game. Do you know what can be my problem? I checked and this problem only happens in the current version.
sorry for my English.

**Comment by johnnypernik** [comment] 2019-07-02 02:01
I agree with this, the problem is something with NUIfocus, if we disable NUIfocus somewhere, like when talking, people can finally at least move, but chat is still dead.

**Comment by Itokoyamato** [comment] 2019-07-02 18:30
Hi there, I've had some reports of that and am very confused as to what could cause this. There isn't any SetNuiFocus in TokoVOIP so I am still unable to pinpoint what could cause such issue.
If anyone has a clue or reproduction case, i'll be happy to check it out.

**Comment by linuxgemini** [comment] 2019-07-02 18:53
We had a *similar* issue where we couldn't manage to get our F key menus working.

**Comment by LucasR0cha** [comment] 2019-07-02 19:35
I found where the problem comes from is in script.js
receivedClientCall - line 127 to 178.

let the timeout like this
if (timeout> = 10 && lastRetry> = 10) {

leaves the chat open or some panel waits a while and will be locked if it opens again or tries to close

**Comment by Itokoyamato** [comment] 2019-07-02 19:43
@LucasR0cha Thanks, that seems to produce the issue alright. I'll be looking to fix it

**Comment by Itokoyamato** [comment] 2019-07-02 21:25
Issue should be fixed [here](https://github.com/Itokoyamato/TokoVOIP_TS3/commit/b910069d1c27857d1ca7002d0fde1003b3f30821)
The script was sometimes spamming NUI callbacks to send data to the LUA, and it appears NUI breaks when too many callbacks are queued
Now the script should send NUI callbacks only if data changed

A new [release](https://github.com/Itokoyamato/TokoVOIP_TS3/releases) has been made.

**Closed by Itokoyamato** 2019-07-02 21:25 UTC
Labels: bug
